### ISSUE TITLE
tal:repeat very slow

### ISSUE THREAD

**Issue by lakano** [jhiver/template-tal#5]
Hello,

Thanks for your package, it's really useful, I'm using TAL template from others languages from many years ago, it's pretty cool to see it now on NodeJS :+1: 

But I have a list of about 600 elements with a simple tal:repeat, and I need to wait about 40 to 60 seconds for TAL processing :-/

If I only keep: `<div tal:repeat="list self.list"></div>` this already take 6 ~ 8 seconds 

Do you have an idea of how we could optimize your code ?

Thanks

**Comment by jhiver** [comment]
Hello and sorry for the super slow reply. Yes I'm pretty sure the problem lies here:

    function shallowCopy (item) {
        return JSON.parse(JSON.stringify(item));
    }

Related to https://github.com/jhiver/template-tal/pull/3

**Comment by jhiver** [comment]
Hello. Could you take a look at the newer version, which should solve the issue. Feel free to reopen if the problem persists.
